timesteps: [0,201]

blur_kernel_size: 51
system_g: 3

name: "${dataset}_${exp_setting}_ubp_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 271
        z_dim: ${z_dim}
        timesteps: ${timesteps}

data:
  data_dir: /home/yueming/Data/THINGS-MEG/Preprocessed_data
  selected_ch: False
  model_type: ${vision_backbone}
  train_batch_size: 1024
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: True
  blur_type:
    target: base.inpating_data.FoveaBlur
    params:
          h: 224
          w: 224
          blur_kernel_size: ${blur_kernel_size}
          curve_type: exp
          system_g:  ${system_g}

  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}
  
save_dir: 'exp'