timesteps: [0,250]

name: "${dataset}_${exp_setting}_baseline_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 63
        z_dim: ${z_dim}
        timesteps: ${timesteps}

data:
  data_dir: /home/yueming/Data/Things-EEG2/Preprocessed_data_250Hz_whiten
  selected_ch: None
  model_type: ${vision_backbone}
  train_batch_size: 1024
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: False
  blur_type:
    target: base.inpating_data.DirectT
    params: {}
  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}

save_dir: 'exp'