timesteps: [0,250]

name: "${exp_setting}_baseline_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 17
        z_dim: ${z_dim}
        timesteps: ${timesteps}

data:
  data_dir: /home/yueming/Data/THINGS-MEG/Preprocessed_data
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']
  model_type: ${vision_backbone}
  train_batch_size: 1024
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: False
  blur_type:
    target: base.inpating_data.DirectT
    params: {}
  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}

save_dir: 'exp'